name = "buner-ff"

main = "src/index.js"

compatibility_date = "2026-08-20"

[vars]
ADMIN_TOKEN = "YOUR_TOKEN_HERE"

[[d1_databases]]
binding = "DB"
database_name = "bunerff-db"
database_id = "0fc730f9-34a3-46e7-9508-fd8d505a916e"

[assets]
directory = "./"
binding = "ASSETS"